# Generated by Django 2.1.7 on 2019-03-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190316_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
                ('isPublic', models.BooleanField()),
                ('creatorEmail', models.EmailField(max_length=254)),
                ('useNum', models.IntegerField()),
            ],
            options={
                'ordering': ['creatorEmail'],
            },
        ),
    ]
