# Generated by Django 2.1.7 on 2019-03-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='path',
            field=models.ImageField(upload_to='tmpImages/'),
        ),
    ]
