# Generated by Django 2.1.7 on 2019-03-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190331_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='tmpImages/')),
            ],
        ),
        migrations.AlterField(
            model_name='models',
            name='path',
            field=models.CharField(max_length=256),
        ),
    ]
