# Generated by Django 2.1.7 on 2019-04-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pictures_ipaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='ipAddress',
            new_name='ip',
        ),
    ]
