# Generated by Django 2.1.7 on 2019-04-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190401_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='uploaded_time',
            field=models.CharField(default='0000000000', max_length=128),
        ),
    ]
