# Generated by Django 2.1.7 on 2019-04-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pictures_uploaded_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='uploaded_time',
            new_name='uploaded_timeStamp',
        ),
    ]
